### ISSUE TITLE
Trouble with icons

### ISSUE THREAD

**Issue by not-a-dev-stein** [sukhmeetbawa/shell-theme-upstream#1]
I'm sorry if the issue ends up being unrelated to the patch, but after applying the current version to my system (the version after adding the rounded corner option) I've been having trouble on both systems (both running the latest Fedora 35) I tried it on with icons, both on regular Adwaita and adwaita-git. A lot of icons are missing, showing this placeholder in its place:

![Captura de tela de 2022-02-05 15-38-16](https://user-images.githubusercontent.com/63420929/152654819-b92f1bea-a927-4ef6-bb75-be9a14223f01.png)

The ones I found out until now are:

- Passowrd prompts' "eye" icon to show/hide your password;
- The notification dot (the one that shows beside the clock on the top bar to show you have new notifications);
- The close icon in the overview (the one in the screenshot above);
- Color picker;

Another one I found missing was the notification bell icon in the notification area:

![Captura de tela de 2022-02-05 15-42-54](https://user-images.githubusercontent.com/63420929/152654925-a14aa43e-a2b1-4f8c-a6ae-9b108a07398b.png)

Beyond that, I've been wondering how is your system using the updated icons in the screenshots (for the battery, volume, etc.). Tried both the regular Adwaita and compiling adwaita-git and nothing makes the system switch to the new ones.

**Comment by sukhmeetbawa** [comment]
It because of [this commit](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/0e3ddb1f020ff81cfa38540926f8c34130d25303). I will fix it later

**Comment by sukhmeetbawa** [comment]
I have fixed the issue with latest commit. Please close the issue if it is working for you now.

**Comment by not-a-dev-stein** [comment]
Yeah, it works now, thanks for the help!

I just need to ask one more time, 'cause those new icons are really pretty lol

> I've been wondering how is your system using the updated icons in the screenshots (for the battery, volume, etc.). Tried both the regular Adwaita and compiling adwaita-git and nothing makes the system switch to the new ones.

**Comment by SilverMarcs** [comment]
You could install `adwaita-icon-theme-git` from the AUR or Chaotic-AUR if you're on Arch. Not sure how you can do so on Fedora but you can try checking out the PKGBUILD from AUR and see if you can build it yourself.

> Beyond that, I've been wondering how is your system using the updated icons in the screenshots (for the battery, volume, etc.). Tried both the regular Adwaita and compiling adwaita-git and nothing makes the system switch to the new ones.

**Comment by not-a-dev-stein** [comment]
> you can try checking out the PKGBUILD from AUR and see if you can build it yourself.

That's what I've been doing, but still no luck, which is weird, because I can check the theme folder and I see that all the new icons are there, they're just not being used.

**Comment by sukhmeetbawa** [comment]
For icons you will have to install it in another folder and change the icon name from Adwaita in index.theme only then I was able to get the new icons. 
And for gdm set icon theme with
`sudo -u gdm gsettings set org.gnome.desktop.interface icon-theme YourIconName`. Also closing issue as problem is solved.
